apiVersion: v2
appVersion: 1.0.4
description: A Helm chart for deploying tangogql-ariadne on Kubernetes
name: ska-tango-tangogql-ariadne
version: 1.0.4
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-base
  version: 0.4.15
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
